# Generated by Django 5.1.1 on 2024-10-01 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwars', '0003_alter_race_options_race_homeplanet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя')),
                ('fraction', models.TextField(verbose_name='Фракция')),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='starwars.race')),
            ],
            options={
                'verbose_name': 'Джедай',
                'verbose_name_plural': 'Джедаи',
            },
        ),
        migrations.DeleteModel(
            name='Jedi',
        ),
    ]
