# Generated by Django 5.1.1 on 2024-10-08 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwars', '0004_character_delete_jedi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('periodInLive', models.TextField(verbose_name='Период существования')),
            ],
            options={
                'verbose_name': 'Фракция',
                'verbose_name_plural': 'Фракции',
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('population', models.TextField(verbose_name='Популяция')),
            ],
            options={
                'verbose_name': 'Планета',
                'verbose_name_plural': 'Планеты',
            },
        ),
        migrations.CreateModel(
            name='Starships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('type', models.TextField(verbose_name='Тип корабля')),
                ('crew', models.TextField(verbose_name='Экипаж корабля')),
            ],
            options={
                'verbose_name': 'Звёздный корабль',
                'verbose_name_plural': 'Звёздные корабли',
            },
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
        migrations.AlterField(
            model_name='character',
            name='fraction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='starwars.fraction'),
        ),
        migrations.AlterField(
            model_name='race',
            name='homePlanet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='starwars.planet'),
        ),
    ]
