# Generated by Django 5.1.1 on 2024-10-08 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starwars', '0005_fraction_planet_starships_alter_character_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Starships',
            new_name='Starship',
        ),
    ]
