# Generated by Django 5.1.1 on 2024-10-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwars', '0006_rename_starships_starship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='fraction',
            field=models.TextField(verbose_name='Фракции'),
        ),
    ]
