# Generated by Django 5.1.1 on 2024-10-08 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwars', '0008_alter_race_homeplanet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='fraction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='starwars.fraction'),
        ),
        migrations.AlterField(
            model_name='race',
            name='homePlanet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='starwars.planet'),
        ),
    ]
