# Generated by Django 5.1.1 on 2024-11-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwars', '0009_alter_character_fraction_alter_race_homeplanet'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='picture',
            field=models.ImageField(null=True, upload_to='starwars', verbose_name='Изображение'),
        ),
    ]
