# Generated by Django 5.1.1 on 2024-11-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwars', '0010_character_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='starship',
            name='picture',
            field=models.ImageField(null=True, upload_to='starships', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='character',
            name='picture',
            field=models.ImageField(null=True, upload_to='characters', verbose_name='Изображение'),
        ),
    ]
